---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.worker.component }}-{{ .Values.commit }}"
  labels:
    {{- template "labels.common" . }}
    component: {{ .Values.worker.component }}
  annotations:
    {{- template "annotations.common" . }}
spec:
  ports:
    - name: worker
      protocol: TCP
      port: 8793
  selector:
    app: {{ .Chart.Name }}
    component: {{ .Values.worker.component }}
