---
## Climgrid image.
##
image:
  registry: localhost:4444
  repository: climgrid
  tag: "latest"

## Configuration values for Climgrid Worker components.
##
worker:
  component: worker
  cmd: celery multi -A climgrid -l info 4 -c 20 --autoscale=15,4

  ## Number of replicas.
  ##
  replicas: 1

  ## Configure resource requests and limits.
  ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 4
      memory: "512Mi"

## Configuration values for the redis dependency.
## ref: https://github.com/kubernetes/charts/blob/master/stable/redis/README.md
##
redis:
  tag: 4.0.9
  usePassword: false

db:
  cloudsql:
    instanceConnectionName: mdzhang-dev:us-central1:mz-climgrid-2
